In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import TruncatedSVD

from sklearn import metrics

import scripts.blosc_interface as bi
import scripts.corpus_split as cs

https://stackoverflow.com/questions/26826002/adding-words-to-stop-words-list-in-tfidfvectorizer-in-sklearn
https://stackoverflow.com/questions/50756085/how-to-print-the-progress-of-a-list-comprehension-in-python
https://stackoverflow.com/questions/57983431/whats-the-most-space-efficient-way-to-compress-serialized-python-data

In [2]:
full_corpus = bi.blosc_read("./data/tokenized_corpus.dat")

In [3]:
x_train, x_test, y_train, y_test = cs.corpus_split(full_corpus)


Splitting the Data into Train and Test


In [4]:
log_reg_cv_results = bi.blosc_read("./data/log_grid_search_result.dat")
log_reg_top5 = log_reg_cv_results.query("rank_test_score <= 5")
log_reg_top5

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
9       64.123026      3.714061  ...        0.008093                5
14      58.169902      0.920133  ...        0.009823                1
18      12.827075      0.430348  ...        0.008752                3
35      11.156855      0.467028  ...        0.009052                4
38      12.062435      0.280006  ...        0.008005                2

[5 rows x 17 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
# Loading Up the Same Pipeline as Random Search
# Updated Values to Optimized
log_clf = Pipeline([
            ('vect', CountVectorizer()),
            ('tfidf', TfidfTransformer()),
            ("svd", TruncatedSVD()),
            ('log_clf', LogisticRegression())
        ])

# Fitting the Optimized Log Reg Model
log_clf.fit(x_train, y_train)

# Getting Predictions on the testset
predicted = log_clf.predict(x_test)
np.mean(predicted == y_test)

# Printing the results
print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)


              precision    recall  f1-score   support

   left-wing       0.55      0.37      0.44      2097
  right-wing       0.55      0.72      0.62      2255

    accuracy                           0.55      4352
   macro avg       0.55      0.55      0.53      4352
weighted avg       0.55      0.55      0.54      4352



array([[ 777, 1320],
       [ 630, 1625]])

In [6]:
# Loading Up the Same Pipeline as Random Search
# Updated Values to Optimized
log_opt_clf = Pipeline([
            ('vect', CountVectorizer(max_features=400, ngram_range=(1,2))),
            ('tfidf', TfidfTransformer()),
            ("svd", TruncatedSVD(n_components=60)),
            ('log_clf', LogisticRegression(penalty="l1", solver = 'saga', C=21.544347, max_iter=1000)), # this needs to be a different solver for LASSO
        ])

# Fitting the Optimized Log Reg Model
log_opt_clf.fit(x_train, y_train)

# Getting Predictions on the testset
predicted = log_opt_clf.predict(x_test)
np.mean(predicted == y_test)

# Printing the results
print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.86      0.84      0.85      2097
  right-wing       0.86      0.88      0.87      2255

    accuracy                           0.86      4352
   macro avg       0.86      0.86      0.86      4352
weighted avg       0.86      0.86      0.86      4352



array([[1762,  335],
       [ 278, 1977]])

https://scikit-learn.org/stable/auto_examples/compose/plot_digits_pipe.html#sphx-glr-auto-examples-compose-plot-digits-pipe-py

In [7]:
# Taken from Sklearn's Auto Examples
# Plot the Truncated SVD spectrum
import matplotlib.pyplot as plt

fig, (ax0, ax1) = plt.subplots(nrows=2, sharex=True, figsize=(6, 6))
ax0.plot(
    np.arange(1, log_clf[2].n_components + 1), log_clf[2].explained_variance_ratio_, "+", linewidth=2
)
ax0.set_ylabel("PCA explained variance ratio")

ax0.axvline(
    log_clf[2].n_components,
    linestyle=":",
    label="n_components chosen",
)
ax0.legend(prop=dict(size=12))

# For each number of components, find the best classifier results
results = log_reg_cv_results
components_col = "param_svd__n_components"
best_clfs = results.groupby(components_col).apply(
    lambda g: g.nlargest(1, "mean_test_score")
)

best_clfs.plot(
    x=components_col, y="mean_test_score", yerr="std_test_score", legend=False, ax=ax1
)
ax1.set_ylabel("Classification accuracy (val)")
ax1.set_xlabel("n_components")

plt.xlim(-1, 70)

plt.tight_layout()
plt.show()


In [8]:
svc_reg_cv_results = bi.blosc_read("./data/svc_grid_search_result.dat")
svc_top5 = svc_reg_cv_results.query("rank_test_score <= 5")
svc_top5

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
5        9.538747      0.252239  ...        0.008687                2
12       8.757007      0.317715  ...        0.007575                5
14      40.221779      1.873627  ...        0.008649                1
24      10.407523      0.389623  ...        0.007222                2
39      42.016662      1.504122  ...        0.009019                4

[5 rows x 18 columns]

In [9]:
from sklearn.svm import LinearSVC

svc_clf = Pipeline([
            ('vect', CountVectorizer()),
            ('tfidf', TfidfTransformer()),
            ("svd", TruncatedSVD()),
            ('svc_clf', LinearSVC()),
        ])

svc_clf.fit(x_train, y_train)

predicted = svc_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.55      0.37      0.45      2097
  right-wing       0.55      0.72      0.62      2255

    accuracy                           0.55      4352
   macro avg       0.55      0.55      0.54      4352
weighted avg       0.55      0.55      0.54      4352



array([[ 783, 1314],
       [ 633, 1622]])

In [12]:
svc_opt_clf = Pipeline([
            ('vect', CountVectorizer(max_features=400, ngram_range=(1,2))),
            ('tfidf', TfidfTransformer()),
            ("svd", TruncatedSVD(n_components=45)),
            ('svc_clf', LinearSVC(penalty = "l2", C = 0.046415)),
        ])

svc_opt_clf.fit(x_train, y_train)

predicted = svc_opt_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.86      0.83      0.85      2097
  right-wing       0.85      0.88      0.86      2255

    accuracy                           0.85      4352
   macro avg       0.85      0.85      0.85      4352
weighted avg       0.85      0.85      0.85      4352



array([[1736,  361],
       [ 274, 1981]])

In [13]:
knn_reg_cv_results = bi.blosc_read("./data/knn_grid_search_result.dat")
knn_top5 = knn_reg_cv_results.query("rank_test_score <= 5")
knn_top5

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
2        7.708155      0.123026  ...        0.004470                1
7       38.017391      0.497011  ...        0.005889                4
10       8.183979      0.187956  ...        0.004015                3
27      38.280288      0.235090  ...        0.004530                2
35       8.004029      0.397554  ...        0.006206                5

[5 rows x 17 columns]

In [14]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = Pipeline([
        ('vect', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ("svd", TruncatedSVD()),
        ('knn_clf', KNeighborsClassifier()),
    ])

knn_clf.fit(x_train, y_train)

predicted = knn_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.54      0.52      0.53      2097
  right-wing       0.57      0.59      0.58      2255

    accuracy                           0.56      4352
   macro avg       0.55      0.55      0.55      4352
weighted avg       0.55      0.56      0.55      4352



array([[1092, 1005],
       [ 930, 1325]])

In [15]:
knn_opt_clf = Pipeline([
        ('vect', CountVectorizer(max_features=400, ngram_range=(1,1))),
        ('tfidf', TfidfTransformer()),
        ("svd", TruncatedSVD(n_components=60)),
        ('knn_clf', KNeighborsClassifier(n_neighbors = 5)),
    ])

knn_opt_clf.fit(x_train, y_train)

predicted = knn_opt_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.87      0.82      0.85      2097
  right-wing       0.84      0.89      0.87      2255

    accuracy                           0.86      4352
   macro avg       0.86      0.86      0.86      4352
weighted avg       0.86      0.86      0.86      4352



array([[1724,  373],
       [ 248, 2007]])

In [16]:
forest_cv_results = bi.blosc_read("./data/forest_grid_search_result.dat")
forest_top5 = forest_cv_results.query("rank_test_score <= 5")
forest_top5

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
1       44.538229      0.430227  ...        0.008400                3
11      11.257121      0.414312  ...        0.007545                5
25      44.256173      0.485781  ...        0.008457                1
29      43.861682      0.323839  ...        0.006240                2
32      12.100364      0.267698  ...        0.007501                4

[5 rows x 19 columns]

In [17]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = Pipeline([
        ('vect', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ("svd", TruncatedSVD()),
        ('forest_clf', RandomForestClassifier()),
    ])

forest_clf.fit(x_train, y_train)

predicted = forest_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.55      0.54      0.54      2097
  right-wing       0.58      0.58      0.58      2255

    accuracy                           0.56      4352
   macro avg       0.56      0.56      0.56      4352
weighted avg       0.56      0.56      0.56      4352



array([[1142,  955],
       [ 952, 1303]])

In [19]:
forest_opt_clf = Pipeline([
        ('vect', CountVectorizer(max_features=400, ngram_range=(1,2))),
        ('tfidf', TfidfTransformer()),
        ("svd", TruncatedSVD(n_components=60)),
        ('forest_clf', RandomForestClassifier(max_features="log2",max_depth=35,
        criterion="entropy")), 
    ])

forest_opt_clf.fit(x_train, y_train)

predicted = forest_opt_clf.predict(x_test)
np.mean(predicted == y_test)

print(metrics.classification_report(y_test, predicted))

metrics.confusion_matrix(y_test, predicted)

              precision    recall  f1-score   support

   left-wing       0.88      0.86      0.87      2097
  right-wing       0.87      0.89      0.88      2255

    accuracy                           0.88      4352
   macro avg       0.88      0.88      0.88      4352
weighted avg       0.88      0.88      0.88      4352



array([[1796,  301],
       [ 239, 2016]])